name: Ci
on: [push]
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          cache: false
          go-version: "1.20"
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.53
  func-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.20"
      - name: get test program
        run: go get -u -v github.com/mailcourses/technopark-dbms-forum@master
      - name: build test program
        run: go build github.com/mailcourses/technopark-dbms-forum
      - name: run app
        run: make run
      - name: run func tests
        run: ./technopark-dbms-forum func -u http://localhost:5000/api
